@url = http://localhost:8080/api/plot
@jwt = eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJwbGFudC1wYXJlbnRzIiwic3ViIjoiYWRtaW4iLCJhcHBVc2VySWQiOjIsImF1dGhvcml0aWVzIjpbIkFETUlOIl0sImV4cCI6MTY4MDYyMTA1MX0.miyoMkhXN20_U8i2mwbuZP_z-phM14oFFmp42REMtrQ

###

GET {{url}} HTTP/1.1

###

GET {{url}}/1 HTTP/1.1

### 

POST {{url}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "name": "New Plot",
    "communityId": 1
}

###

PUT {{url}}/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "plotId": 1,
    "name": "Updated Plot",
    "communityId": 2
}

###

DELETE {{url}}/1 HTTP/1.1
Authorization: Bearer {{jwt}}

###

POST http://localhost:8080/authenticate HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}