#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Oct 16 15:33:03 2019

@author: Giles
"""

# 1 Ask the user for the radius of a circle and then print the area



# 2 Convert fahrenheit to celsius (You will have to find the formula)

# far = float(input('Enter a fahrenheit degree: '))
# cel = (far - 32) * 0.5556
# print(far, 'degrees fahrenheit is ' , cel , 'degrees celsius')


# 3 Obtain the sum of two integers

# first = int(input('Enter first number: '))
# second = int(input('Enter second number: '))
# sum = first + second
# print('The sum of', first, 'and', second, 'is', total)


# 4 Obtain the product of two integers


# first = int(input('Enter first number: '))
# second = int(input('Enter second number: '))
# product = first * second
# print('The product of', first, 'and', second, 'is', product)


# 5 Bob, Ann, Jane and Ashwin want to order pizza - they know they will each eat
# 4 slices of pizza. The local pizza shop sells pizzas of only 6 slices
# What is the minimum number of pizzas needed - Use floor division

total = 4 *4
number_of_pies = (total + 5) //

